---
title: "Toy Example with Adaptive Substitution Analysis"
author: "Hanxi Sun"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# setwd("~/GoogleDrive/Purdue/Research/Vinayak_Rao/17Spr_Genetic/Softwares/myPhast/myTest/")
```

## Toy Data
```{r, eval=FALSE, engine='bash'}
ALPHABET: A C G T 
LENGTH: ~ 100,000 bp 
BACKGROUND: 0.325828 0.191345 0.182691 0.300136 
RATE_MAT: 
  -0.805948    0.144819    0.512276    0.148853  
   0.246602   -1.248680    0.160256    0.841822  
   0.913638    0.167846   -1.331401    0.249917  
   0.161594    0.536683    0.152123   -0.850401  
TREE: ((human:0.103078,(mouse:0.0751206,rat:0.0788608):0.279636):0.101507,cow:0.101507);
```


```{r, echo=FALSE}
# ## Get Adaptive Substitution

# read .fasta
fa <- readLines("../hmrc.fa")

# preprocessing
sp.loc <- which(startsWith(fa, '> ')) # species names locations in .fasta file
num_row <- sp.loc[2] - sp.loc[1] - 1  # num of rows of sequ for each species
sequ <- sapply(split(fa[-sp.loc],     # DNA sequences
                     rep(1:length(sp.loc), each=num_row)), 
               function(x) strsplit(paste(x, collapse = ''), ''))
sequ <- do.call(cbind.data.frame, sequ)
sp.name <- sapply(fa[sp.loc],         # species names 
                  function(x) substring(x, 3))
colnames(sequ) <- sp.name

# adaptive substitution locations
### count for all adaptive substitutions
as.loc <- which((sequ$human != sequ$mouse) & (sequ$mouse == sequ$rat) & (sequ$mouse == sequ$cow))
### no insertion (other species = '-')
as.loc1 <- which((sequ$human != sequ$mouse) & (sequ$mouse == sequ$rat) & (sequ$mouse == sequ$cow) & (sequ$mouse != '-'))
### no insertion or deletion
as.loc2 <- which((sequ$human != sequ$mouse) & (sequ$mouse == sequ$rat) & (sequ$mouse == sequ$cow) & (sequ$mouse != '-') &  (sequ$human != '-'))
```


## Original DLESS (phyloHMM) output
```{r, echo=FALSE}
# ## Preprocessing DLESS (phyloHMM) output (.gff)

# abbrev types to 'conserve', 'death' or 'acc'
type.abbrev <- function(t){
    sapply(as.character(t), function(x){a<-unlist(strsplit(x, '-')); a[length(a)]})
    # t1 <- sapply(as.character(t), function(x){a<-unlist(strsplit(x, '-')); a[length(a)]})
    # t1[t1 %in% c('death', 'conserved')] <- 'con'
}

# the original output (rho=0.3, phi=0.5)
df <- read.table("../original_hmrc.gff", skip=3)
gff0 <- df[,c("V3","V4","V5")]
colnames(gff0) <- c("type", "start", "end")
gff0$type.ab <- type.abbrev(gff0$type)

gff0[,1:3]
```

## Modified DLESS output
```{r, echo=FALSE}
# output from 
# ../bin/dless --acc-height 2 --lambda 2.5 --phi 0.2 --eta 0.3 hmrc.fa hky.mod > v2_accH.gff
df <- read.table("v2_accH.gff", skip=3)
gff <- df[,c("V3","V4","V5")]
colnames(gff) <- c("type", "start", "end")
gff$type.ab <- type.abbrev(gff$type)

gff[,1:3]
```


## Plots on the Chain
```{r, echo=FALSE, message=FALSE, fig.height=4}
library(ggplot2)
# pdf('v2_test_1.pdf')
orig.y <- 50; new.y <- 150 # y loc for the labels
plot.h <- 
    ggplot(as.data.frame(as.loc), aes(as.loc)) +
    geom_histogram(bins = 50) + 
    geom_segment(aes(x = start, y = orig.y, 
                     xend = end, yend = orig.y,
                     colour = type.ab), 
                 size = 3, data = gff0)+ 
    geom_segment(aes(x = start, y = new.y, 
                     xend = end, yend = new.y,
                     colour = type.ab), 
                 size = 3, data = gff) + 
    labs(x = 'Location', title = 'adaptive sub counts with insertion & deletion') +
    geom_label(data = data.frame(x = rep(5000, 2), 
                                y = c(orig.y, new.y), 
                                lab = c("original", "with acc")),
              aes(x,y,label = lab), fill = 'lightsteelblue4', colour = "white", fontface = "bold")
plot.h
# dev.off()

# pdf('v2_test_2.pdf')
orig.y <- 3; new.y <- 9
plot.h <- 
    ggplot(as.data.frame(as.loc1), aes(as.loc1)) +
    geom_histogram(bins = 50) + 
    geom_segment(aes(x = start, y = orig.y, 
                     xend = end, yend = orig.y,
                     colour = type.ab), 
                 size = 3, data = gff0)+ 
    geom_segment(aes(x = start, y = new.y, 
                     xend = end, yend = new.y,
                     colour = type.ab), 
                 size = 3, data = gff) + 
    labs(x = 'Location', title = 'adaptive sub counts with only deletion') +
    geom_label(data = data.frame(x = rep(5000, 2), 
                                 y = c(orig.y, new.y), 
                                 lab = c("original", "with acc")),
               aes(x,y,label = lab), fill = 'lightsteelblue4', colour = "white", fontface = "bold") +
    xlim(0, max(as.loc1))
plot.h
# dev.off()

# pdf('v2_test_3.pdf')
orig.y <- 4; new.y <- 8
plot.h <- 
    ggplot(as.data.frame(as.loc2), aes(as.loc2)) +
    geom_histogram(bins = 50) + 
    geom_segment(aes(x = start, y = orig.y, 
                     xend = end, yend = orig.y,
                     colour = type.ab), 
                 size = 3, data = gff0)+ 
    geom_segment(aes(x = start, y = new.y, 
                     xend = end, yend = new.y,
                     colour = type.ab), 
                 size = 3, data = gff) + 
    labs(x = 'Location', title = 'adaptive sub counts without insertion or deletion') +
    geom_label(data = data.frame(x = rep(5000, 2), 
                                 y = c(orig.y, new.y), 
                                 lab = c("original", "with acc")),
               aes(x,y,label = lab), fill = 'lightsteelblue4', colour = "white", fontface = "bold") +
    xlim(0, max(as.loc2))
plot.h
# dev.off()
```



## Plots on the Conserved/Accelerated Regions

```{r, echo=FALSE, message=FALSE, fig.height=4}
regions <- unlist(apply(gff[,2:3], 1, function(x) seq(x[1], x[2], by=1)))
regions0 <- unlist(apply(gff0[,2:3], 1, function(x) seq(x[1], x[2], by=1)))
    
gff.adj <- gff
gff0.adj <- gff0

gff.adj$adj.start <- gff.adj$start
gff.adj$adj.end <- gff.adj$end
gff0.adj$adj.start <- gff0.adj$start
gff0.adj$adj.end <- gff0.adj$end

adj.para <- 50 
adj <- cumsum( gff.adj$end - gff.adj$start + adj.para )
gff.adj$adj.start <- c(0, adj[1:length(adj)-1]) + 700
gff.adj$adj.end <- gff.adj$adj.start + gff.adj$end - gff.adj$start

for(i in 1:nrow(gff0.adj)){
    a <- gff0.adj$adj.start[i] 
    k <- max(which(a >= gff.adj$start))
    gff0.adj$adj.start[i] <- a - gff.adj$start[k] + gff.adj$adj.start[k]
    
    b <- gff0.adj$adj.end[i] 
    k <- min(which(b <= gff.adj$end))
    gff0.adj$adj.end[i] <- b - gff.adj$start[k] + gff.adj$adj.start[k]
}


adj.as.loc <- function(loc){
    loc1 <- loc[loc %in% c(regions, regions0)]
    for(i in 1:length(loc1)){
        a <- loc1[i]
        k <- max(which(a >= gff.adj$start))
        loc1[i] <- a - gff.adj$start[k] + gff.adj$adj.start[k]
    }
    loc1
}

as.loc.adj <- adj.as.loc(as.loc)
as.loc1.adj <- adj.as.loc(as.loc1)
as.loc2.adj <- adj.as.loc(as.loc2)


library(ggplot2)
# pdf('v2_test_1.pdf')

orig.y <- 3; new.y <- 7 # y loc for the labels
plot.h <- 
    ggplot(as.data.frame(as.loc.adj), aes(as.loc.adj)) +
    geom_histogram(bins = 100) + 
    geom_segment(aes(x = adj.start, y = orig.y, 
                     xend = adj.end, yend = orig.y,
                     colour = type.ab), 
                 size = 3, data = gff0.adj)+ 
    geom_segment(aes(x = adj.start, y = new.y, 
                     xend = adj.end, yend = new.y,
                     colour = type.ab), 
                 size = 3, data = gff.adj) + 
    labs(x = 'Relative Location', title = 'adaptive sub counts with insertion & deletion on CON/ACC regions') +
    geom_label(data = data.frame(x = rep(200, 2), 
                                y = c(orig.y, new.y), 
                                lab = c("original", "with acc")),
              aes(x,y,label = lab), fill = 'lightsteelblue4', colour = "white", fontface = "bold") +
    xlim(0, max(gff.adj$adj.end + adj.para))
plot.h
# dev.off()

# pdf('v2_test_2.pdf')
orig.y <- 1; new.y <- 1.5
plot.h <-  
    ggplot(as.data.frame(as.loc1.adj), aes(as.loc1.adj)) +
    geom_histogram(binwidth = 75) + 
    geom_segment(aes(x = adj.start, y = orig.y, 
                     xend = adj.end, yend = orig.y,
                     colour = type.ab), 
                 size = 3, data = gff0.adj)+ 
    geom_segment(aes(x = adj.start, y = new.y, 
                     xend = adj.end, yend = new.y,
                     colour = type.ab), 
                 size = 3, data = gff.adj) + 
    labs(x = 'Location', title = 'adaptive sub counts with only deletion on CON/ACC regions') +
    geom_label(data = data.frame(x = rep(200, 2), 
                                 y = c(orig.y, new.y), 
                                 lab = c("original", "with acc")),
               aes(x,y,label = lab), fill = 'lightsteelblue4', colour = "white", fontface = "bold") +
    xlim(0, max(gff.adj$adj.end + adj.para))
plot.h
# dev.off()

# pdf('v2_test_3.pdf')
orig.y <- 1; new.y <- 1.3
plot.h <- 
    ggplot(as.data.frame(as.loc2.adj), aes(as.loc2.adj)) +
    geom_histogram(binwidth = 75) + 
    geom_segment(aes(x = adj.start, y = orig.y, 
                     xend = adj.end, yend = orig.y,
                     colour = type.ab), 
                 size = 3, data = gff0.adj)+ 
    geom_segment(aes(x = adj.start, y = new.y, 
                     xend = adj.end, yend = new.y,
                     colour = type.ab), 
                 size = 3, data = gff.adj) + 
    labs(x = 'Location', title = 'adaptive sub counts without insertion or deletion on CON/ACC regions') +
    geom_label(data = data.frame(x = rep(200, 2), 
                                 y = c(orig.y, new.y), 
                                 lab = c("original", "with acc")),
               aes(x,y,label = lab), fill = 'lightsteelblue4', colour = "white", fontface = "bold") +
    xlim(0, max(gff.adj$adj.end + adj.para))
plot.h
# dev.off()
```









```{r, echo=FALSE, eval=FALSE}
## Tests

# preprocessing AS & Neutral
as <- as1 <- as2 <- rep('AS', nrow(sequ))
as[as.loc] <- as1[as.loc1] <- as2[as.loc2] <- 'nonAS'
neutral <- neutral0 <- rep('Neutral', nrow(sequ))
neutral[Reduce(c, 
               apply(cbind(gff$start, gff$end), 1, 
                     function(x) x[1]:x[2]))] <- 'nonNeutral'
neutral0[Reduce(c, 
                apply(cbind(gff0$start, gff0$end), 1, 
                      function(x) x[1]:x[2]))] <- 'nonNeutral'

prop.test(table(neutral0, as))  # original output & all AS
prop.test(table(neutral, as))   # new output & all AS

prop.test(table(neutral0, as1)) # original output & AS w/o deletion
prop.test(table(neutral, as1))  # new output & AS w/o deletion

prop.test(table(neutral0, as2)) # original output & AS w/o deletion or insertion
prop.test(table(neutral, as2))  # new output & AS w/o deletion or insertion

```
